### ISSUE TITLE
Red text color in body paragraphs

### ISSUE THREAD

**Issue by lantzbuilds** [learn-co-curriculum/python-p3-sql-queries#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/pages/sql-queries?module_item_id=468011

### Concern

On Canvas, on the bottom half of the page, all of the body text is colored red. (looks like it persists from the header)

### Suggested Changes

Fix formatting so body paragraph on bottom of page are black to match top half of page.

**Comment by professor-ben** [comment]
Yeesh! Thanks for the report. This is fixed and will be synced next week.
